version: '3.9'

services:
  database_kimbundo:
    image: postgres
    container_name: database_kimbundo
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kimbundo
      - POSTGRES_PASSWORD=kimbundo
      - POSTGRES_DB=kimbundo
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: kimbundo
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - database_kimbundo
    depends_on:
      - database_kimbundo

volumes:
  pgdata:
    driver: local
